/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package facturaventa;


public class Factura extends javax.swing.JFrame {

    
    public Factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jResultado = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtProducto1 = new javax.swing.JTextField();
        txtProducto2 = new javax.swing.JTextField();
        txtProducto3 = new javax.swing.JTextField();
        txtVlrUnitario1 = new javax.swing.JTextField();
        txtVlrUnitario2 = new javax.swing.JTextField();
        txtVlrUnitario3 = new javax.swing.JTextField();
        txtCantidad1 = new javax.swing.JTextField();
        txtCantidad2 = new javax.swing.JTextField();
        txtCantidad3 = new javax.swing.JTextField();
        txtVlrTotal1 = new javax.swing.JTextField();
        txtVlrTotal2 = new javax.swing.JTextField();
        txtVlrTotal3 = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JTextField();
        BtnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ORDEN DE COMPRA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel2.setText("Cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        jLabel3.setText("Producto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel4.setText("Vlr.Unitario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        jLabel5.setText("Cantidad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        jResultado.setText("JlabelResultado:");
        jPanel1.add(jResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 10));

        jLabel7.setText("VlrTotal:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jLabel8.setText("Valor Total:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));
        jPanel1.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 180, -1));
        jPanel1.add(txtProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 170, -1));
        jPanel1.add(txtProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 170, -1));
        jPanel1.add(txtProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 170, -1));
        jPanel1.add(txtVlrUnitario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 110, -1));
        jPanel1.add(txtVlrUnitario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 110, -1));
        jPanel1.add(txtVlrUnitario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 110, -1));
        jPanel1.add(txtCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 80, -1));
        jPanel1.add(txtCantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 80, -1));
        jPanel1.add(txtCantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 80, -1));

        txtVlrTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVlrTotal1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtVlrTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 110, -1));
        jPanel1.add(txtVlrTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 110, -1));
        jPanel1.add(txtVlrTotal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 110, -1));
        jPanel1.add(txtValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 110, -1));

        BtnCalcular.setBackground(new java.awt.Color(102, 102, 102));
        BtnCalcular.setText("CALCULAR");
        BtnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCalcularMouseClicked(evt);
            }
        });
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
       //Declaraciones de variables para tipo entero
        
       int num1;
       int num2;
       int total;
       
       int ValorTotal1;
       int ValorTotal2;
       int ValorTotal3;
       
       int Resultado;
       //Total valor unitario 1
       num1=Integer.parseInt(txtVlrUnitario1.getText());
       num2=Integer.parseInt(txtCantidad1.getText());
       total = num1* num2;
        txtVlrTotal1.setText(String.valueOf(total));
       //Total valor unitario 2
       
       num1=Integer.parseInt(txtVlrUnitario2.getText());
       num2=Integer.parseInt(txtCantidad2.getText());
       total = num1* num2;
       txtVlrTotal2.setText(String.valueOf(total));
       //Total valor unitario 3
      
       num1=Integer.parseInt(txtVlrUnitario3.getText());
       num2=Integer.parseInt(txtCantidad3.getText());
       total = num1* num2;
       txtVlrTotal3.setText(String.valueOf(total));
       //Transformación de los 3 valores unitarios a enteros
       
       ValorTotal1= Integer.parseInt(txtVlrTotal1.getText());
       ValorTotal2= Integer.parseInt(txtVlrTotal2.getText());
       ValorTotal3= Integer.parseInt(txtVlrTotal3.getText());
       //Vaariables de valores unitarios "resultado"
       Resultado = ValorTotal1 + ValorTotal2 + ValorTotal3;
       //Mostrar la suma de los valores unitarios a valor total
       txtValorTotal.setText(String.valueOf(Resultado));
       String Cliente = txtCliente.getText();
       jResultado.setText("Señor(a):"+ Cliente+"El total de su compra es:"+"$");
      
       
        
    }//GEN-LAST:event_BtnCalcularActionPerformed

    private void BtnCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCalcularMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCalcularMouseClicked

    private void txtVlrTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVlrTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVlrTotal1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jResultado;
    private javax.swing.JTextField txtCantidad1;
    private javax.swing.JTextField txtCantidad2;
    private javax.swing.JTextField txtCantidad3;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtProducto1;
    private javax.swing.JTextField txtProducto2;
    private javax.swing.JTextField txtProducto3;
    private javax.swing.JTextField txtValorTotal;
    private javax.swing.JTextField txtVlrTotal1;
    private javax.swing.JTextField txtVlrTotal2;
    private javax.swing.JTextField txtVlrTotal3;
    private javax.swing.JTextField txtVlrUnitario1;
    private javax.swing.JTextField txtVlrUnitario2;
    private javax.swing.JTextField txtVlrUnitario3;
    // End of variables declaration//GEN-END:variables
}
